CREATE TABLE IF NOT EXISTS master.tenants
(
    id              BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 10000 INCREMENT BY 1) NOT NULL,
    tenant_name     VARCHAR(255) NOT NULL,

    status          VARCHAR(50) NOT NULL DEFAULT 'PROVISIONING',

    /*
        PROVISIONING
        READY
        SUSPENDED
        PROVISIONING_FAILED
        DELETING
        DELETED
     */

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_tenants PRIMARY KEY (id)
);