export const CustomerTableConfig = {
    "table_key" : "customers_table_1234",
    "display_name" : "Customer Management",
    "add_button_label" : "+ Add Customer",
    "table_api" : {
        "table_config_api" : "/identity/management/customers/config/table",
        "columns_config_api" : "/identity/management/customers/config/columns",
        "actions_config_api" : "/identity/management/customers/config/actions",
        "header_config_api" : "/identity/management/customers/config/header",
        "row_actions_config_api" : "/identity/management/customers/config/row-actions",
        "paginated_data_api" : "/identity/management/customers",
        "create_api" : "/identity/management/customers/create",
        "create_all_api" : "/identity/management/customers/create/all",
        "create_bulk_api" : "/identity/management/customers/create/bulk",
        "create_import_api" : "/identity/management/customers/create/import",
        "data_api" : "/identity/management/customers/:id",
        "update_api" : "/identity/management/customers/update/:id",
        "update_bulk_api" : "/identity/management/customers/update/bulk",
        "update_all_api" : "/identity/management/customers/update/all",
        "update_status_api" : "/identity/management/customers/update/status",
        "update_bulk_status_api" : "/identity/management/customers/update/bulk/status",
        "update_import_api" : "/identity/management/customers/update/import",
        "delete_api" : "/identity/management/customers/delete/:id",
        "delete_all_api" : "/identity/management/customers/delete/all",
        "delete_bulk_api" : "/identity/management/customers/delete/bulk",
        "export_data_api" : "/identity/management/customers/export",
        "download_data_api" : "/identity/management/customers/download",
        "list_view_api" : "/identity/management/customers/view/list",
        "save_view_api" : "/identity/management/customers/view/create",
        "get_view_api" : "/identity/management/customers/view/:id",
        "delete_view_api" : "/identity/management/customers/view/:id",
        "default_view_api" : "/identity/management/customers/view/:id/default",
        "live_talk_api" : "/identity/management/customers/talk",
        "live_listen_api" : "/identity/management/customers/listen",
        "lock_get_api" : "/identity/management/customers/lock",
        "lock_table_api" : "/identity/management/customers/lock/table",
        "lock_rows_api" : "/identity/management/customers/lock/rows",
        "ai_summary_api" : "/identity/management/customers/ai/summary",
        "ai_interact_api" : "/identity/management/customers/ai/interact"
    },
    "show_title_header_section" : true,
    "enable_add_data_button" : true,
    "show_table_headers" : true,
    "enable_table_search_filters" : true,
    "enable_row_level_checkboxes" : true,
    "enable_master_level_checkbox" : true,
    "min_height" : "380px",
    "max_height" : "calc(100vh - 240px)",
    "editable_single_multiple_selected_rows" : true,
    "editable_all_rows" : true,
    "action_panel" : true,
    "action_column" : {
        "active" : true,
        "options" : [
            "refresh",
            "disable",
            "revert",
            "view",
            "pin / unpin",
            "lock",
            "edit",
            "delete"
        ]
    },
    "rows": {
        "row_expansion" : false,
        "freez" : false
    },
    "pagination": {
        "active" : true,
        "default_page_size" : 10,
        "page_size_options" : [10, 25, 50, 100]
    }
};
