export const CustomerColumnConfig = {
    customer_code: {
        header_name: "Customer Code",
        filter_key: "customer_code",
        columns: { customers: "customer_code" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 1,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Customer Code field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 1,
            horizontal_section: "h_section_1",
            required: true,
            error_note: "Customer Code is required",
            info_note: "Enter customer code"
        },
        freez: { freez_side: "left", order: 1 },
        filter_data: []
    },
    customer_name: {
        header_name: "Customer Name",
        filter_key: "customer_name",
        columns: { customers: "customer_name" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 2,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Customer Name field",
        elipsis: "text_elipsis",
        active: true,
        width: "190px",
        modal: {
            order: 2,
            horizontal_section: "h_section_1",
            required: true,
            error_note: "Customer Name is required",
            info_note: "Enter customer name"
        },
        freez: { freez_side: "left", order: 2 },
        filter_data: []
    },
    legal_name: {
        header_name: "Legal Name",
        filter_key: "legal_name",
        columns: { customers: "legal_name" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 3,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Legal Name field",
        elipsis: "text_elipsis",
        active: true,
        width: "190px",
        modal: {
            order: 3,
            horizontal_section: "h_section_2",
            required: false,
            error_note: "Legal Name is required",
            info_note: "Enter legal name"
        },
        filter_data: []
    },
    email: {
        header_name: "Email",
        filter_key: "email",
        columns: { customers: "email" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 4,
        column_resize: true,
        cell_mode: "text_code_2000",
        info_note: "Email field",
        elipsis: "text_elipsis",
        active: true,
        width: "240px",
        modal: {
            order: 4,
            horizontal_section: "h_section_2",
            required: false,
            error_note: "Email is required",
            info_note: "Enter email"
        },
        filter_data: []
    },
    phone: {
        header_name: "Phone",
        filter_key: "phone",
        columns: { customers: "phone" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 5,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Phone field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 5,
            horizontal_section: "h_section_3",
            required: false,
            error_note: "Phone is required",
            info_note: "Enter phone"
        },
        filter_data: []
    },
    status: {
        header_name: "Status",
        filter_key: "status",
        columns: { customers: "status" },
        filter_type: "list",
        editable: true,
        sorting: true,
        order: 6,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Status field",
        elipsis: "text_elipsis",
        active: true,
        width: "140px",
        modal: {
            order: 6,
            horizontal_section: "h_section_3",
            required: false,
            error_note: "Status is required",
            info_note: "Enter status"
        },
        filter_data: [
            { key: "active", name: "Active" },
            { key: "inactive", name: "Inactive" },
            { key: "pending", name: "Pending" }
        ]
    },
    industry: {
        header_name: "Industry",
        filter_key: "industry",
        columns: { customers: "industry" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 7,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Industry field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 7,
            horizontal_section: "h_section_4",
            required: false,
            error_note: "Industry is required",
            info_note: "Enter industry"
        },
        filter_data: []
    },
    country: {
        header_name: "Country",
        filter_key: "country",
        columns: { customers: "country" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 8,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Country field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 8,
            horizontal_section: "h_section_4",
            required: false,
            error_note: "Country is required",
            info_note: "Enter country"
        },
        filter_data: []
    },
    country_code: {
        header_name: "Country Code",
        filter_key: "country_code",
        columns: { customers: "country_code" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 9,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Country Code field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 9,
            horizontal_section: "h_section_5",
            required: false,
            error_note: "Country Code is required",
            info_note: "Enter country code"
        },
        filter_data: []
    },
    city: {
        header_name: "City",
        filter_key: "city",
        columns: { customers: "city" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 10,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "City field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 10,
            horizontal_section: "h_section_5",
            required: false,
            error_note: "City is required",
            info_note: "Enter city"
        },
        filter_data: []
    },
    state: {
        header_name: "State",
        filter_key: "state",
        columns: { customers: "state" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 11,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "State field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 11,
            horizontal_section: "h_section_6",
            required: false,
            error_note: "State is required",
            info_note: "Enter state"
        },
        filter_data: []
    },
    address: {
        header_name: "Address",
        filter_key: "address",
        columns: { customers: "address" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 12,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Address field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 12,
            horizontal_section: "h_section_6",
            required: false,
            error_note: "Address is required",
            info_note: "Enter address"
        },
        filter_data: []
    },
    postal_code: {
        header_name: "Postal Code",
        filter_key: "postal_code",
        columns: { customers: "postal_code" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 13,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Postal Code field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 13,
            horizontal_section: "h_section_7",
            required: false,
            error_note: "Postal Code is required",
            info_note: "Enter postal code"
        },
        filter_data: []
    },
    website: {
        header_name: "Website",
        filter_key: "website",
        columns: { customers: "website" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 14,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Website field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 14,
            horizontal_section: "h_section_7",
            required: false,
            error_note: "Website is required",
            info_note: "Enter website"
        },
        filter_data: []
    },
    annual_revenue: {
        header_name: "Annual Revenue",
        filter_key: "annual_revenue",
        columns: { customers: "annual_revenue" },
        filter_type: "number_range",
        editable: true,
        sorting: true,
        order: 15,
        column_resize: true,
        cell_mode: "text_code_3000",
        info_note: "Annual Revenue field",
        elipsis: "text_elipsis",
        active: true,
        width: "150px",
        modal: {
            order: 15,
            horizontal_section: "h_section_8",
            required: false,
            error_note: "Annual Revenue is required",
            info_note: "Enter annual revenue"
        },
        filter_data: []
    },
    currency: {
        header_name: "Currency",
        filter_key: "currency",
        columns: { customers: "currency" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 16,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Currency field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 16,
            horizontal_section: "h_section_8",
            required: false,
            error_note: "Currency is required",
            info_note: "Enter currency"
        },
        filter_data: []
    },
    employee_count: {
        header_name: "Employee Count",
        filter_key: "employee_count",
        columns: { customers: "employee_count" },
        filter_type: "number_range",
        editable: true,
        sorting: true,
        order: 17,
        column_resize: true,
        cell_mode: "text_code_3000",
        info_note: "Employee Count field",
        elipsis: "text_elipsis",
        active: true,
        width: "150px",
        modal: {
            order: 17,
            horizontal_section: "h_section_9",
            required: false,
            error_note: "Employee Count is required",
            info_note: "Enter employee count"
        },
        filter_data: []
    },
    owner_name: {
        header_name: "Owner Name",
        filter_key: "owner_name",
        columns: { customers: "owner_name" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 18,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Owner Name field",
        elipsis: "text_elipsis",
        active: true,
        width: "190px",
        modal: {
            order: 18,
            horizontal_section: "h_section_9",
            required: false,
            error_note: "Owner Name is required",
            info_note: "Enter owner name"
        },
        filter_data: []
    },
    owner_email: {
        header_name: "Owner Email",
        filter_key: "owner_email",
        columns: { customers: "owner_email" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 19,
        column_resize: true,
        cell_mode: "text_code_2000",
        info_note: "Owner Email field",
        elipsis: "text_elipsis",
        active: true,
        width: "240px",
        modal: {
            order: 19,
            horizontal_section: "h_section_10",
            required: false,
            error_note: "Owner Email is required",
            info_note: "Enter owner email"
        },
        filter_data: []
    },
    risk_level: {
        header_name: "Risk Level",
        filter_key: "risk_level",
        columns: { customers: "risk_level" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 20,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Risk Level field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 20,
            horizontal_section: "h_section_10",
            required: false,
            error_note: "Risk Level is required",
            info_note: "Enter risk level"
        },
        filter_data: []
    },
    customer_type: {
        header_name: "Customer Type",
        filter_key: "customer_type",
        columns: { customers: "customer_type" },
        filter_type: "search",
        editable: true,
        sorting: true,
        order: 21,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Customer Type field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 21,
            horizontal_section: "h_section_11",
            required: false,
            error_note: "Customer Type is required",
            info_note: "Enter customer type"
        },
        filter_data: []
    },
    onboarding_date: {
        header_name: "Onboarding Date",
        filter_key: "onboarding_date",
        columns: { customers: "onboarding_date" },
        filter_type: "date_range",
        editable: true,
        sorting: true,
        order: 22,
        column_resize: true,
        cell_mode: "text_code_4000",
        info_note: "Onboarding Date field",
        elipsis: "text_elipsis",
        active: true,
        width: "160px",
        modal: {
            order: 22,
            horizontal_section: "h_section_11",
            required: false,
            error_note: "Onboarding Date is required",
            info_note: "Enter onboarding date"
        },
        filter_data: []
    },
    last_activity_at: {
        header_name: "Last Activity At",
        filter_key: "last_activity_at",
        columns: { customers: "last_activity_at" },
        filter_type: "date_range",
        editable: true,
        sorting: true,
        order: 23,
        column_resize: true,
        cell_mode: "text_code_4000",
        info_note: "Last Activity At field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 23,
            horizontal_section: "h_section_12",
            required: false,
            error_note: "Last Activity At is required",
            info_note: "Enter last activity at"
        },
        filter_data: []
    },
    is_active: {
        header_name: "Is Active",
        filter_key: "is_active",
        columns: { customers: "is_active" },
        filter_type: "list",
        editable: true,
        sorting: true,
        order: 24,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Is Active field",
        elipsis: "text_elipsis",
        active: true,
        width: "140px",
        modal: {
            order: 24,
            horizontal_section: "h_section_12",
            required: false,
            error_note: "Is Active is required",
            info_note: "Enter is active"
        },
        filter_data: [
            { key: "active", name: "Active" },
            { key: "inactive", name: "Inactive" },
            { key: "pending", name: "Pending" }
        ]
    },
    editable: {
        header_name: "Editable",
        filter_key: "editable",
        columns: { customers: "editable" },
        filter_type: "list",
        editable: true,
        sorting: true,
        order: 25,
        column_resize: true,
        cell_mode: "text_code_1000",
        info_note: "Editable field",
        elipsis: "text_elipsis",
        active: true,
        width: "140px",
        modal: {
            order: 25,
            horizontal_section: "h_section_13",
            required: false,
            error_note: "Editable is required",
            info_note: "Enter editable"
        },
        filter_data: [
            { key: "active", name: "Active" },
            { key: "inactive", name: "Inactive" },
            { key: "pending", name: "Pending" }
        ]
    },
    created_at: {
        header_name: "Created At",
        filter_key: "created_at",
        columns: { customers: "created_at" },
        filter_type: "date_range",
        editable: false,
        sorting: true,
        order: 26,
        column_resize: true,
        cell_mode: "text_code_4000",
        info_note: "Created At field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 26,
            horizontal_section: "h_section_13",
            required: false,
            error_note: "Created At is required",
            info_note: "Enter created at"
        },
        filter_data: []
    },
    updated_at: {
        header_name: "Updated At",
        filter_key: "updated_at",
        columns: { customers: "updated_at" },
        filter_type: "date_range",
        editable: false,
        sorting: true,
        order: 27,
        column_resize: true,
        cell_mode: "text_code_4000",
        info_note: "Updated At field",
        elipsis: "text_elipsis",
        active: true,
        width: "180px",
        modal: {
            order: 27,
            horizontal_section: "h_section_14",
            required: false,
            error_note: "Updated At is required",
            info_note: "Enter updated at"
        },
        filter_data: []
    }
};

export const CustomerColumnOptionsConfig = {
    pin: {
        key: "pin",
        name: "pin",
        active: true,
        info_note: "Pin column to left freeze side or unpin"
    },
    readonly: {
        key: "readonly",
        name: "readonly",
        active: true,
        info_note: "Toggle column editable / readonly mode"
    },
    hide: {
        key: "hide",
        name: "hide",
        active: true,
        info_note: "Hide or show column in table view"
    }
};
