CREATE TABLE IF NOT EXISTS products
(
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    identifier VARCHAR(100) NOT NULL UNIQUE,

    description TEXT,

    status VARCHAR(50) NOT NULL DEFAULT 'active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );